### PR TITLE
Add statistics and PASS/FAIL status based on change in result value to performance tests

### PR DESCRIPTION
**Pull request by leivos-unikie**
Report test PASS/FAIL based on the actual results, not only based on success in running the test commands.

### CODE REVIEW

**Comment by leivos-unikie** [comment]
@azbeleva, this is now ready for your review and test runs in the dev test setup

**Comment by leivos-unikie** [comment]
For now the threshold values are hardcoded in Robot-Framework/lib/PerformanceDataProcessing.py. In the future it would be nice to have separate file containing threshold for each performance parameter. I have tuned the threshold values based on production line test result history but I believe we need to tune them more after having some more experience.

**Comment by leivos-unikie** [comment]
This PR does not change the current csv result files and how result data is added to those. Instead it creates a separate statistics file for each test into new "statistics" directory. For now those statistics files are mainly for debugging and following the deviation history. They are overwritten (recalculated based on given threshold values) each time a corresponding test is run.

**Comment by leivos-unikie** [comment]
> For now the threshold values are hardcoded in Robot-Framework/lib/PerformanceDataProcessing.py. In the future it would be nice to have separate file containing threshold for each performance parameter. I have tuned the threshold values based on production line test result history but I believe we need to tune them more after having some more experience.

I moved the threshold settings to Robot-Framework/lib/performance_thresholds.py

**Review by azbeleva — APPROVED** [review]

**Comment by leivos-unikie** [comment]
I noticed a bug in assigning correct threshold value for single/multi thread and write/read tests in VMs. Because tests for VMs have different naming convention than the tests for ghaf-host I had to make these changes to PerformanceDataProcessing.py

line 183
```
        # Set threshold for fail depending on test type: single/multi thread
        if "One thread" in test_name or "1thread" in test_name:
            threshold = thresholds['cpu']['single']
        else:
            threshold = thresholds['cpu']['multi']
```

line 296
```
        # Set threshold for fail depending on test type: single/multi thread, write/read
        if "One thread" in test_name or "1thread" in test_name:
            if "rite" in test_name:
                threshold = thresholds['mem']['single']['wr']
            else:
                threshold = thresholds['mem']['single']['rd']
        else:
            if "rite" in test_name:
                threshold = thresholds['mem']['multi']['wr']
            else:
                threshold = thresholds['mem']['multi']['rd']
```

**Pull request merged**
